"""Process raw work photos from photo-work/ into optimized WebP for the landing page.

For every known module folder in <repo>/photo-work/ this script:
  1. Applies EXIF orientation and center-crops to a square.
  2. Writes 1024x1024 WebP (lightbox) and 640x640 WebP (marquee thumb)
     into frontend/public/works/<slug>/.
  3. Regenerates the typed manifest frontend/src/lib/landing/works-photos.ts.

Re-run it whenever photos are added or changed (e.g. when the missing
"Градиент" / "Аэрография" folders appear) — output is fully regenerated.

Usage (from repo root, requires Pillow):
    python scripts/works_photos/process.py
"""

import shutil
import sys
from pathlib import Path

from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "photo-work"
OUT = ROOT / "frontend" / "public" / "works"
MANIFEST = ROOT / "frontend" / "src" / "lib" / "landing" / "works-photos.ts"

# Order matches module order in frontend/src/lib/landing/course-content.ts.
FOLDER_TO_SLUG = {
    "Фольга": "folga",
    "Аквариум": "akvarium",
    "Втирка": "vtirka",
    "Слайдеры и наклейки": "slaidery",
    "Френч": "french",
    "Пигменты": "pigmenty",
    "Градиент": "gradient",
    "Стемпингъ": "stemping",
    "Стразы и фигурки": "strazy",
    "Текстуры": "tekstury",
    "Аэрография": "aerografiya",
}

FULL_SIZE = 1024
THUMB_SIZE = 640
EXTS = {".jpg", ".jpeg", ".png", ".webp"}


def process_folder(folder: str, slug: str) -> list[str]:
    src_dir = SRC / folder
    if not src_dir.is_dir():
        print(f"  skip {slug}: no folder {src_dir.name!r} yet")
        return []

    files = sorted(p for p in src_dir.iterdir() if p.suffix.lower() in EXTS)
    skipped = sorted(p.name for p in src_dir.iterdir() if p.is_file() and p.suffix.lower() not in EXTS)
    if skipped:
        print(f"  WARNING {slug}: unsupported files skipped: {', '.join(skipped)}")
    if not files:
        print(f"  skip {slug}: folder is empty")
        return []

    out_dir = OUT / slug
    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True)

    stems: list[str] = []
    for i, path in enumerate(files, 1):
        with Image.open(path) as im:
            im = ImageOps.exif_transpose(im).convert("RGB")
            full = ImageOps.fit(im, (FULL_SIZE, FULL_SIZE), Image.LANCZOS)
        thumb = full.resize((THUMB_SIZE, THUMB_SIZE), Image.LANCZOS)
        stem = f"{slug}-{i:02d}"
        full.save(out_dir / f"{stem}.webp", "WEBP", quality=80, method=6)
        thumb.save(out_dir / f"{stem}-thumb.webp", "WEBP", quality=75, method=6)
        stems.append(stem)
    print(f"  {slug}: {len(stems)} photos from {folder!r}")
    return stems


def write_manifest(entries: dict[str, list[str]]) -> None:
    lines = [
        "// AUTO-GENERATED by scripts/works_photos/process.py — DO NOT EDIT",
        "",
        "export interface WorkPhoto {",
        "  thumb: string;",
        "  full: string;",
        "}",
        "",
        "export const worksPhotos: Record<string, WorkPhoto[]> = {",
    ]
    for slug, stems in entries.items():
        if not stems:
            continue
        lines.append(f"  {slug}: [")
        for stem in stems:
            lines.append(
                f'    {{ thumb: "/works/{slug}/{stem}-thumb.webp", full: "/works/{slug}/{stem}.webp" }},'
            )
        lines.append("  ],")
    lines.append("};")
    lines.append("")
    MANIFEST.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def main() -> int:
    if not SRC.is_dir():
        print(f"Source folder not found: {SRC}")
        return 1

    print("Processing work photos...")
    entries = {slug: process_folder(folder, slug) for folder, slug in FOLDER_TO_SLUG.items()}
    write_manifest(entries)

    modules = sum(1 for stems in entries.values() if stems)
    photos = sum(len(stems) for stems in entries.values())
    total_bytes = sum(f.stat().st_size for f in OUT.rglob("*.webp"))
    print(f"Done: {modules} modules, {photos} photos, {total_bytes / 1024 / 1024:.1f} MB in {OUT}")
    print(f"Manifest: {MANIFEST}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
