"""add_lesson_content

Revision ID: 2f3f813eeb34
Revises: a1ca77add764
Create Date: 2026-01-24 01:05:20.186749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f3f813eeb34'
down_revision: Union[str, None] = 'a1ca77add764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'content')
    # ### end Alembic commands ###
